backend = "full"
colorspace = "lab"
palette = "dark"

[templates.colors_json]
template = "colors.json"
target = "~/.cache/wal/colors.json"

[templates.colors_sh]
template = "colors.sh"
target = "~/.cache/wal/colors.sh"

[templates.sequences]
template = "sequences"
target = "~/.cache/wal/sequences"

[templates.kitty]
template = "kitty.conf"
target = "~/.config/kitty/pywal-colors.conf"

[templates.zed_theme]
template = "zed.json"
target = "~/.config/zed/themes/wallust.json"
